// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoradaGuia.API.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MoradaGuia.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191111192330_MessageEntityAdded")]
    partial class MessageEntityAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MoradaGuia.API.Models.Imovel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bairro");

                    b.Property<DateTime>("Data");

                    b.Property<int>("Garagem");

                    b.Property<int>("Numero");

                    b.Property<int>("QtdBanheiro");

                    b.Property<int>("QtdQuarto");

                    b.Property<string>("Rua");

                    b.Property<string>("Tipo");

                    b.Property<int>("UserId");

                    b.Property<float>("Valor");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Imovel");
                });

            modelBuilder.Entity("MoradaGuia.API.Models.Like", b =>
                {
                    b.Property<int>("LikerId");

                    b.Property<int>("ImovelLikeId");

                    b.HasKey("LikerId", "ImovelLikeId");

                    b.HasIndex("ImovelLikeId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("MoradaGuia.API.Models.Messages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<DateTime?>("DateRead");

                    b.Property<bool>("IsRead");

                    b.Property<DateTime>("MessageSent");

                    b.Property<bool>("RecipientDeleted");

                    b.Property<int>("RecipientId");

                    b.Property<bool>("SenderDeleted");

                    b.Property<int>("SenderId");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("MoradaGuia.API.Models.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ImovelId");

                    b.Property<bool>("Principal");

                    b.Property<string>("PublicId");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("ImovelId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("MoradaGuia.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Criado");

                    b.Property<string>("Email");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<DateTime>("UltimoLogin");

                    b.Property<string>("Username");

                    b.Property<string>("telefone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MoradaGuia.API.Models.Imovel", b =>
                {
                    b.HasOne("MoradaGuia.API.Models.User")
                        .WithMany("Imovels")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MoradaGuia.API.Models.Like", b =>
                {
                    b.HasOne("MoradaGuia.API.Models.Imovel", "ImovelLike")
                        .WithMany("Liker")
                        .HasForeignKey("ImovelLikeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MoradaGuia.API.Models.User", "Liker")
                        .WithMany("ImovelLike")
                        .HasForeignKey("LikerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MoradaGuia.API.Models.Messages", b =>
                {
                    b.HasOne("MoradaGuia.API.Models.User", "Recipient")
                        .WithMany("MessagesReceived")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MoradaGuia.API.Models.User", "Sender")
                        .WithMany("MessagesSent")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MoradaGuia.API.Models.Photo", b =>
                {
                    b.HasOne("MoradaGuia.API.Models.Imovel", "Imovel")
                        .WithMany("Fotos")
                        .HasForeignKey("ImovelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
